### ISSUE TITLE
Trang chủ

### ISSUE THREAD

**Issue by honggaj** [honggaj/TreeStore#2]
Code giao diện trang chủ đẹp đẹp xíu

**Comment by tamntm39** [comment]
Đơn giản và dễ hiểu: Giao diện trang chủ nên có cấu trúc rõ ràng, dễ dàng cho người dùng điều hướng và tìm thấy thông tin một cách nhanh chóng.
Hình ảnh và màu sắc hấp dẫn: Sử dụng màu sắc phù hợp để tạo cảm giác thân thiện 
Giao diện thân thiện với người dùng
